import os
SECRET_KEY = os.urandom(32)
# Grabs the folder where the script runs.
basedir = os.path.abspath(os.path.dirname(__file__))

# Enable debug mode.
DEBUG = True

# Connect to the database


# TODO IMPLEMENT DATABASE URL
DB_NAME="test_capstone"
# DB_NAME="capstone"
# SQLALCHEMY_DATABASE_URI = 'postgresql://jiazhang@localhost:5432/fyyur'
SQLALCHEMY_DATABASE_URI =f"postgresql://postgres@localhost:5432/{DB_NAME}"
SQLALCHEMY_TRACK_MODIFICATIONS = False

# RBAC tokens
casting_assistant="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InVSaVptcFJxUHR1eW1nSWEwRktXMyJ9.eyJpc3MiOiJodHRwczovL2t2emhhbmcudXMuYXV0aDAuY29tLyIsInN1YiI6ImxpbmtlZGlufGdvRktBWFhjVnkiLCJhdWQiOlsiY2Fwc3RvbmUiLCJodHRwczovL2t2emhhbmcudXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY2OTAwMTIzOSwiZXhwIjoxNjY5NjA2MDM5LCJhenAiOiJOUU9QNGVDeG9iSVlzQ0hZM2hYZGxaWXRIVDJDQlU3YiIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJwZXJtaXNzaW9ucyI6WyJhZGQ6YWN0b3JzIiwiYWRkOm1vdmllcyIsImRlbGV0ZTphY3RvcnMiLCJkZWxldGU6bW92aWVzIiwibW9kaWZ5OmFjdG9ycyIsIm1vZGlmeTptb3ZpZXMiLCJ2aWV3OmFjdG9ycyIsInZpZXc6bW92aWVzIl19.XNYwEhfHULo6VcrMLXab9f4AbQxVa_4Y7hH27M_yoBm8pzKudFt6kE9UhMk1o_WjeQmi28njyU4s3GAgNVj34arPpok1X01RAnI6AqwEUEtdQ2UwAtKCsZyWkNrKo3VfXe5z-enAmXueogaqpWp3v7XkYVi1EWP61vFyrqodjVJCGKwxTlsc45mw6tJBNty5G9tYSUxjaN0GFCeZTvpBcUiTPKz2BszbSs-YnKK2z2RswiK8yi948SdwwNia93n9AoJx_J57mlrkgxuwiWiauKWxMtNnDJdhqQU92EQx9TPwP0n0TCHI-HBM0YYP8wpSXd_cBClJaDu3LXYUk2wKgQ"
executive_producer=""
casting_director=""
