"""Flask configuration."""
from dotenv import load_dotenv
from os import path,getenv
# Grabs the folder where the script runs.
basedir = path.abspath(path.dirname(__file__))
load_dotenv(path.join(basedir, '.env'))

# Define SECRET_KEY for app.config
# SECRET_KEY set with os.urandom(32) will cause app hit http 500(ISE) during authentication on heroku deployment, use fix string to fix it
# https://stackoverflow.com/questions/30984622/flask-session-not-persistent-across-requests-in-flask-app-with-gunicorn-on-herok
#SECRET_KEY = os.urandom(32)
#APP_SECRET_KEY=ALongRandomlyGeneratedString
SECRET_KEY=getenv("APP_SECRET_KEY")

# Enable debug mode.
DEBUG = True
# Connect to the database


# local production DB info
# lower case for db_* , otherwise it will be picked up by flask app.config with useless configuration
db_name="capstone"
db_user='postgres'
db_password='postgres'
db_host="localhost:5432"
db_path = f"postgresql://{db_user}:{db_password}@{db_host}/{db_name}"
SQLALCHEMY_DATABASE_URI =db_path
# SQLALCHEMY_DATABASE_URI =f"postgresql://{db_user}:{db_password}@{db_host}/{db_name}"
SQLALCHEMY_TRACK_MODIFICATIONS = False

#test db env
test_db_name = getenv("TEST_DATABASE_NAME")
test_db_user=getenv("DATABASE_USER")
test_db_password = getenv("DATABASE_PASS")
test_db_path = f"postgresql://{test_db_user}:{test_db_password}@localhost:5432/{test_db_name }"

# RBAC tokens
casting_assistant="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InVSaVptcFJxUHR1eW1nSWEwRktXMyJ9.eyJpc3MiOiJodHRwczovL2t2emhhbmcudXMuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYzNDEzN2Q4OGQzZWY2NjJlMDI4MjYyZSIsImF1ZCI6WyJjYXBzdG9uZSIsImh0dHBzOi8va3Z6aGFuZy51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjcwNDA1MTMzLCJleHAiOjE2NzEwMDk5MzMsImF6cCI6Ik5RT1A0ZUN4b2JJWXNDSFkzaFhkbFpZdEhUMkNCVTdiIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInBlcm1pc3Npb25zIjpbInZpZXc6YWN0b3JzIiwidmlldzptb3ZpZXMiXX0.HPqc19CiSBooySlAoeLaNdfw5lJQWEtp-RtVwyQ44vaasQelJbDzGLlVf5z4M3xWC7AqWLl4lNUZ4AZCzCMSqeD_S-Du-yC0e5g_WsYH36C3cjhIeZDWLKCOOiNRYH8yx77G1kLp9spgG4ztl3F_lqnT9jrKyiTpLKuyhcT07FWj8lBRD5a0OG42PTd0YSdf5eLmtyqQRCfBZZIiVuh5sHAewIUC3vMa7uWraQZmWUSULWsloJ3iiku4GpMMD-XKi1zqSGKb5Ujxs73VIyZ7TRUYXXyF2OJJQQ-u3Vx2b408mumB1B4PrHcwl2qblC_iBRn9yrHOzRkHDKJXxHkIiA"
casting_director="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InVSaVptcFJxUHR1eW1nSWEwRktXMyJ9.eyJpc3MiOiJodHRwczovL2t2emhhbmcudXMuYXV0aDAuY29tLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTE0MzIzOTUzMjg0MTg3MDUwNzEzIiwiYXVkIjpbImNhcHN0b25lIiwiaHR0cHM6Ly9rdnpoYW5nLnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NzA0MDUyMDMsImV4cCI6MTY3MTAxMDAwMywiYXpwIjoiTlFPUDRlQ3hvYklZc0NIWTNoWGRsWll0SFQyQ0JVN2IiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwicGVybWlzc2lvbnMiOlsiYWRkOmFjdG9ycyIsImRlbGV0ZTphY3RvcnMiLCJtb2RpZnk6YWN0b3JzIiwibW9kaWZ5Om1vdmllcyIsInZpZXc6YWN0b3JzIiwidmlldzptb3ZpZXMiXX0.Gs8rVvHPUhEzP6RRTtacIWaR187M2aPMOTJqmDDNW0a1lT3BcKPDF1CjkV9febfdsd2r1uGS3mbSZwVQSJHCiJJl73L7w7VuPtqBA3YpA9c6qKHHSYPXjnx_N72rKekz2BQ3bZyVM_xltO2rGj1IaoUbBUd3ZH69lSMyAkHToEWmnhWCWtphLh-dFca2Y3bL5fv4YjrwP_FVuuXkylN4LlqRJ7TIiYrmzYeSTWLzaCMCo2muAanYOnPvPxhcAfcmUY7DEfgqcLhs4lSHxcCU8LRq16ZcM0XAjuE-wjGK3rBoOwbr5FHSv25FZ-nVUUI9sXGoxroTuB7vUdI03eg7HQ"
executive_producer="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InVSaVptcFJxUHR1eW1nSWEwRktXMyJ9.eyJpc3MiOiJodHRwczovL2t2emhhbmcudXMuYXV0aDAuY29tLyIsInN1YiI6ImxpbmtlZGlufGdvRktBWFhjVnkiLCJhdWQiOlsiY2Fwc3RvbmUiLCJodHRwczovL2t2emhhbmcudXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY3MDQwNTI0NSwiZXhwIjoxNjcxMDEwMDQ1LCJhenAiOiJOUU9QNGVDeG9iSVlzQ0hZM2hYZGxaWXRIVDJDQlU3YiIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJwZXJtaXNzaW9ucyI6WyJhZGQ6YWN0b3JzIiwiYWRkOm1vdmllcyIsImRlbGV0ZTphY3RvcnMiLCJkZWxldGU6bW92aWVzIiwibW9kaWZ5OmFjdG9ycyIsIm1vZGlmeTptb3ZpZXMiLCJ2aWV3OmFjdG9ycyIsInZpZXc6bW92aWVzIl19.BS5Bpy_2injYAP8kWjJaxKvn8Vh_i83gCkzby4JDBZ-AKLDCAou3Pd8edj-mEFWWYg2j5h1tx4t1tshxJLkg6vGpfB_P8kuDLpAiev6yZsQr2N04jscplGFSlh75pr4BK1T9HtM3PoUkqPISOMxAYocyb-7uWreRbcHWeebcANYIeHgqgpvsJkvTmYsDHScbf8iZHOPU4HeDdiD--_1wF7DJyrz69tLtB0vtnBEbmcf5rwSngIgstFE2v5vidsbaddOB1Utll4X8YneG1FwUvdEJt8fU9PJqctuB3vAqqPxeF9JojcuhXLS5TnHDV8fuNtSfGGG7WiKuhWyrVFkTwQ"
