"""Flask configuration."""
from dotenv import load_dotenv
from os import path,getenv
# Grabs the folder where the script runs.
basedir = path.abspath(path.dirname(__file__))
load_dotenv(path.join(basedir, '.env'))

# Define SECRET_KEY for app.config
# SECRET_KEY set with os.urandom(32) will cause app hit http 500(ISE) during authentication on heroku deployment, use fix string to fix it
# https://stackoverflow.com/questions/30984622/flask-session-not-persistent-across-requests-in-flask-app-with-gunicorn-on-herok
#SECRET_KEY = os.urandom(32)
#APP_SECRET_KEY=ALongRandomlyGeneratedString
SECRET_KEY=getenv("APP_SECRET_KEY")

# Enable debug mode.
DEBUG = True
# Connect to the database


# local production DB info
# lower case for db_* , otherwise it will be picked up by flask app.config with useless configuration
db_name="capstone"
db_user='postgres'
db_password='postgres'
db_host="localhost:5432"
db_path = f"postgresql://{db_user}:{db_password}@{db_host}/{db_name}"
SQLALCHEMY_DATABASE_URI =db_path
# SQLALCHEMY_DATABASE_URI =f"postgresql://{db_user}:{db_password}@{db_host}/{db_name}"
SQLALCHEMY_TRACK_MODIFICATIONS = False

#test db env
test_db_name = getenv("TEST_DATABASE_NAME")
test_db_user=getenv("DATABASE_USER")
test_db_password = getenv("DATABASE_PASS")
test_db_path = f"postgresql://{test_db_user}:{test_db_password}@localhost:5432/{test_db_name }"

# RBAC tokens
casting_assistant="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InVSaVptcFJxUHR1eW1nSWEwRktXMyJ9.eyJpc3MiOiJodHRwczovL2t2emhhbmcudXMuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYzNDEzN2Q4OGQzZWY2NjJlMDI4MjYyZSIsImF1ZCI6WyJjYXBzdG9uZSIsImh0dHBzOi8va3Z6aGFuZy51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjY5NjA2ODg0LCJleHAiOjE2NzAyMTE2ODQsImF6cCI6Ik5RT1A0ZUN4b2JJWXNDSFkzaFhkbFpZdEhUMkNCVTdiIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInBlcm1pc3Npb25zIjpbInZpZXc6YWN0b3JzIiwidmlldzptb3ZpZXMiXX0.S8bBZoxWF-atfyNUhZ5DAZrpM6p6e0ETK6gzICDZ7doXNFEZmxAC34Hhqs42uoumXVzcKNQRgIcaZhyWKzCCcrhlGUlGxcpqH1quU1F-xfG70IBMhW4OnkZJCQSzcqvV2XlV8Q9YFxtTTV48G__cY3K5pP34407qv2clUerp0bTtYZQcZBPLMly8fTrOhKgwThEP9J0AWHnzIRGUxvhImLJ1AWgPoJG35MVR8xKCnEYInTuV_Qx3USjzKaWVBL3Vj7wUtnfkawESHJe26iEFXdHUuhkXgEir79-YzfNbpbA4IceXCv3BPCoILGbhDl-2oQekb4--hRe6EfWsQI10LA"
casting_director="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InVSaVptcFJxUHR1eW1nSWEwRktXMyJ9.eyJpc3MiOiJodHRwczovL2t2emhhbmcudXMuYXV0aDAuY29tLyIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTE0MzIzOTUzMjg0MTg3MDUwNzEzIiwiYXVkIjpbImNhcHN0b25lIiwiaHR0cHM6Ly9rdnpoYW5nLnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2Njk2MDc0MjcsImV4cCI6MTY3MDIxMjIyNywiYXpwIjoiTlFPUDRlQ3hvYklZc0NIWTNoWGRsWll0SFQyQ0JVN2IiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwicGVybWlzc2lvbnMiOlsiYWRkOmFjdG9ycyIsImRlbGV0ZTphY3RvcnMiLCJtb2RpZnk6YWN0b3JzIiwibW9kaWZ5Om1vdmllcyIsInZpZXc6YWN0b3JzIiwidmlldzptb3ZpZXMiXX0.Hpq5kqylKW4UmGxayx_sdxQolMnCIxn50eJMU6x2JzvRvcRNug4xTDTkBPb_9JkkEkptBvrdr2NsiNaUByWPlWnoVJ4TI0VPXJl9-YRolmzUxoAGk8mgN3wrXJuc_B9HUUXckQXrX9ChdYa4kHhh6ILl6RM-6i4Is1xNMGsdBeGAApqUY0ZXi5eMJ79WNShjzJ7CKjEIujE6UURXdMT2nglQz9QOHGFo4RdrAQor0Msi1d0l8g8ZaveWCjJ8H5RpU5m78BSZKaTKfGqXxJAaZ6D9TO-VcSGUSW2yKj3RKCm0P2H6RmvYCjvoC5nysOJeMYDoTJ9cMoYaGN8H8xx2Ug"
executive_producer="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InVSaVptcFJxUHR1eW1nSWEwRktXMyJ9.eyJpc3MiOiJodHRwczovL2t2emhhbmcudXMuYXV0aDAuY29tLyIsInN1YiI6ImxpbmtlZGlufGdvRktBWFhjVnkiLCJhdWQiOlsiY2Fwc3RvbmUiLCJodHRwczovL2t2emhhbmcudXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY2OTYwNjE4MSwiZXhwIjoxNjcwMjEwOTgxLCJhenAiOiJOUU9QNGVDeG9iSVlzQ0hZM2hYZGxaWXRIVDJDQlU3YiIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJwZXJtaXNzaW9ucyI6WyJhZGQ6YWN0b3JzIiwiYWRkOm1vdmllcyIsImRlbGV0ZTphY3RvcnMiLCJkZWxldGU6bW92aWVzIiwibW9kaWZ5OmFjdG9ycyIsIm1vZGlmeTptb3ZpZXMiLCJ2aWV3OmFjdG9ycyIsInZpZXc6bW92aWVzIl19.gu6gjMs8-O--CkHArDe9919snVrME0eCtmabylQ0LelCRQGCuICENsL3aHCBDfBQvIoTNvSh3prd4xZcr6O53qvTeokHGPKyVKYopAtryThIVTedXohBc4QdUmQhyuYeYc1nwV480xXHNXwkKkW--kKM9pXoKM5-gWmQfuxzUUUeaxKCILVGVnx-4kj9tH90u8nrl74VKovVOCewMK5Uyq4zWKPjkyb2YWNJK-lSUHY6Zzmll6jJfYfUsHaD31mq1azqOR3aADVR4NSCoVqAa30SKHe0CFR7p5QPzgO9KDbbMfDC8r5zxiYUWIgvrIZ4bYW2Kcn8SCNWCqZz6TIxtA"
